### ISSUE TITLE
How did your drone work?

### ISSUE THREAD

**Issue by thepenguinthatwants** [hamdouni/gitea-drone#1]
Hi!
I have being trying to fiddle out how to get gitea and drone work on my traefik quite a while.

Didn't u need to the site for drone by labels?

**Comment by hamdouni** [comment]
Hi.

Sorry, I don't understand your question. Can you reformulate it perhaps by
giving an example ?

Thanks.

Best regards.

Brahim.

**Comment by thepenguinthatwants** [comment]
Hi!

Sorry for the unclear question.

I was trying to get drone to work without succession. I am wondering how your setup didn't have labels. Normally they have these stuff's

    labels:
      - "traefik.enable=true"
      - "traefik.backend=drone"
      - "traefik.docker.network=web"
      - "traefik.frontend.rule=Host:drone.localhost"
 
Is drone accessible by browser? Or are they working background?

**Comment by hamdouni** [comment]
Drone is accessible by browser thru traefik.
You can configure traefik rules like this :
```yaml
[backends]
  [backends.gitea]
    [backends.gitea.servers.server1]
       url = "http://gitea:3000"
  [backends.drone]
    [backends.drone.servers.server1]
       url = "http://drone:8000"
  [backends.osticket]
    [backends.osticket.servers.server1]
       url = "http://osticket"
```

**Comment by thepenguinthatwants** [comment]
Cool I didnt know that was possible.

Do you have a whole docker-compose file with that in it as example?
